--- 
after_success: 
  - "npm run deploy"
branches: 
  only: 
    - master
    - stable
cache: 
  directories: 
    - node_modules
deploy: 
  keep_history: true
  provider: script
  script: scripts/deploy-to-gh-pages.sh
  skip_cleanup: true
  true: 
    branch: master
dist: trusty
env: 
  global: 
    - GITHUB_TOKEN=3dcee82eee4bbe47f62e5626cc4dd44c77c2074a
    - GitHub_REF=github.com/web-front-end/react-hook-todo.git
    - TIMEOUT=1000
language: node_js
node_js: 
  - 8
script: 
  - "npm run test --watchAll"
sudo: false
