--- 
# after_success: 
#   - "npm run deploy"
branches: 
  only: 
    - master
    - stable
cache: 
  directories: 
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
dist: trusty
env: 
  global: 
    - GITHUB_TOKEN=425fc655ca0f21c9f18efd61fda63ae94837a6c6
    - GitHub_REF=github.com/web-front-end/react-hook-todo.git
    - TIMEOUT=1000
language: node_js
node_js: 
  - 8
script: 
  - "npm run test --watchAll"
sudo: false
